Repository ODOICHON/frontend, pull requests merged in 2023-11, with the labels that each got.

#187 Feat/#173 마이페이지 빈집중개 - 내 매물 관리 페이지
  package.json
  src/Routes.tsx
  src/apis/houses.ts
  src/components/Common/NoPosts/index.tsx
  src/components/Common/NoPosts/styles.module.scss
  src/components/Common/Pagination/index.tsx
  src/components/Common/Pagination/styles.module.scss
  src/components/Common/ui/Button/index.tsx
  src/components/Common/ui/Button/styles.module.scss
  src/components/Community/NoPosts/index.tsx
  src/components/MyPage/DealStateModal/index.tsx
  src/components/MyPage/DealStateModal/styles.module.scss
  src/components/MyPage/MyHomePopularCard/index.tsx
  src/components/MyPage/MyHomePopularCard/styles.module.scss
  src/components/MyPage/MyPageNavbar/index.tsx
  src/components/MyPage/MyPageNavbar/styles.module.scss
  src/components/MyPage/MyTradeCard/index.tsx
  src/components/MyPage/MyTradeCard/styles.module.scss
  src/constants/variants.ts
  src/pages/Community/Board/index.tsx
  src/pages/Mypage/home/index.tsx
  src/pages/Mypage/home/styles.module.scss
  src/pages/Mypage/index.tsx
  src/pages/Mypage/styles.module.scss
  src/pages/Mypage/trade/myself/index.tsx
  src/pages/Mypage/trade/myself/styles.module.scss
  src/pages/Trade/Board/index.tsx
  src/pages/Trade/index.tsx
  src/pages/_layout.tsx
  src/queryClient.ts
  src/types/Board/boardType.ts
  src/types/Board/myPageType.ts
  src/types/Board/tradeType.ts
  src/types/user.d.ts
  src/utils/utils.ts
  yarn.lock
Labels: FIX, FEAT

#193 Fix/#190 빈집거래 페이지 상단 필터링(유형, 위치, 검색)에 따라 결과에 제대로 업데이트 되지 않는 버그 수정
  src/components/Common/ui/Button/index.tsx
  src/components/MyPage/MyTradeCard/index.tsx
  src/components/MyPage/MyTradeCard/styles.module.scss
  src/components/Trade/Info/index.tsx
  src/components/Trade/Quill/index.tsx
  src/pages/Mypage/trade/myself/index.tsx
  src/pages/Trade/Board/index.tsx
  src/pages/Trade/Board/styles.module.scss
  src/pages/Trade/Write/index.tsx
  src/pages/Trade/index.tsx
  src/types/Board/boardType.ts
  src/utils/utils.ts
Labels: FIX, REFACTOR

#198 fix: 빈집거래 게시글 상태변경 시 에러 핸들링 처리
  src/apis/houses.ts
  src/components/MyPage/DealStateModal/index.tsx
Labels: FIX

#195 Feat/#194 내가 쓴 글 페이지 구현
  src/Routes.tsx
  src/apis/houses.ts
  src/components/Community/Board/index.tsx
  src/components/Trade/Quill/index.tsx
  src/pages/Mypage/community/write/index.tsx
  src/pages/Mypage/community/write/styles.module.scss
  src/pages/Mypage/trade/scrap/index.tsx
  src/pages/Trade/Write/index.tsx
Labels: FEAT

#201 Feat/#200 빈집거래 게시글 임시저장 API 연동
  src/components/Common/ui/Button/styles.module.scss
  src/components/MyPage/MyTradeCard/styles.module.scss
  src/components/Trade/Quill/index.tsx
  src/pages/Mypage/trade/myself/styles.module.scss
Labels: FIX, FEAT

#207 fix: 불필요한 파일 제거
  src/components/MyPage/MyHomePopularCard/index.tsx
  src/components/Trade/Quill/index.tsx
  src/constants/trade_dummy.ts
  src/types/Board/tradeType.ts
Labels: FIX
