Repository ODOICHON/frontend, pull requests merged in 2023-06, with the labels that each got.

#108 fix: 회원가입 페이지에서 커뮤니티 페이지 이동시 생기는 리스트 스타일 초기화 버그 수정
  src/components/Terms/styles.module.scss
Labels: FIX

#109 Refact/#107 폴더 병합 및 코드 리팩토링
  src/components/Board/CommentDetail/index.tsx
  src/components/Board/CommentDetail/styles.module.scss
  src/components/Board/Comments/index.tsx
  src/components/Board/Comments/styles.module.scss
  src/components/Board/Like/index.tsx
  src/components/Board/Like/styles.module.scss
  src/components/Common/Footer/index.tsx
  src/components/Common/Footer/styles.module.scss
  src/components/Common/Loading/index.tsx
  src/components/Common/Loading/styles.module.scss
  src/components/Common/Navbar/index.tsx
  src/components/Common/Navbar/styles.module.scss
  src/components/Common/Pagenation/index.tsx
  src/components/Common/Pagenation/styles.module.scss
  src/components/Common/Preparation/index.tsx
  src/components/Common/Preparation/styles.module.scss
  src/components/Common/ToggleMenu/index.tsx
  src/components/Common/ToggleMenu/styles.module.scss
  src/components/Community/NoPosts/index.tsx
  src/components/Community/NoPosts/styles.module.scss
  src/components/Login/AfterLogin/index.tsx
  src/components/Login/AfterLogin/styles.module.scss
  src/components/Login/BeforeLogin/index.tsx
  src/components/Login/BeforeLogin/styles.module.scss
  src/hooks/useWindowSize.ts
  src/pages/Community/Board/index.tsx
  src/pages/Community/Detail/index.tsx
  src/pages/Introduce/Board/index.tsx
  src/pages/Mypage/index.tsx
  src/pages/Trade/index.tsx
  src/pages/_layout.tsx
Labels: REFACTOR

#114 Design/#105 모바일 폰트 사이즈 조정
  src/pages/Community/Detail/styles.module.scss
  src/pages/Introduce/Board/styles.module.scss
  src/pages/Main/index.tsx
  src/pages/Main/styles.module.scss
  src/queryClient.ts
  src/reset.scss
Labels: DESIGN

#120 Feat/#117 빈집거래 매물 상세 페이지 UI 구현
  index.html
  package.json
  public/trade_board_test.png
  src/components/Trade/.gitkeep
  src/components/Trade/Info/index.tsx
  src/components/Trade/Info/styles.module.scss
  src/components/Trade/KakaoMapImage/index.tsx
  src/components/Trade/KakaoMapImage/styles.module.scss
  src/pages/Trade/Board/index.tsx
  src/pages/Trade/Board/styles.module.scss
  tsconfig.json
  yarn.lock
Labels: FEAT, DESIGN

#121 Feat/#119 빈집거래 중개 프로세스 페이지 UI 구현
  src/assets/trade/example1.png
  src/assets/trade/example2.png
  src/assets/trade/example3.png
  src/pages/Trade/Process/index.tsx
  src/pages/Trade/Process/styles.module.scss
Labels: FEAT, DESIGN

#127 Design/#126 인용문 blockquote 스타일 수정 및 styles 폴더 생성 및 관리
  src/components/Board/CommentDetail/styles.module.scss
  src/components/Common/Footer/styles.module.scss
  src/components/Common/Navbar/styles.module.scss
  src/components/Community/Board/styles.module.scss
  src/components/Community/Quill/styles.module.scss
  src/components/Introduce/Quill/styles.module.scss
  src/components/Login/AfterLogin/styles.module.scss
  src/components/Login/BeforeLogin/styles.module.scss
  src/components/Trade/BoardCard/index.tsx
  src/components/Trade/Info/styles.module.scss
  src/components/Trade/KakaoMapImage/styles.module.scss
  src/components/Trade/SearchBar/index.tsx
  src/components/Trade/SearchBar/styles.module.scss
  src/main.tsx
  src/pages/Community/Board/styles.module.scss
  src/pages/Community/Detail/styles.module.scss
  src/pages/Community/styles.module.scss
  src/pages/Introduce/Board/styles.module.scss
  src/pages/Introduce/styles.module.scss
  src/pages/Main/styles.module.scss
  src/pages/NotFound/styles.module.scss
  src/pages/SignUp/styles.module.scss
  src/pages/Trade/Board/styles.module.scss
  src/pages/Trade/Process/styles.module.scss
  src/pages/Trade/index.tsx
  src/pages/Trade/styles.module.scss
  src/styles/editor.scss
  src/styles/media.scss
  src/styles/reset.scss
Labels: REFACTOR, DESIGN

#130 Feat/#129 애니매이션 적용 안된 페이지 애니메이션 적용
  src/pages/Community/Board/index.tsx
  src/pages/Community/Detail/index.tsx
  src/pages/Community/Write/index.tsx
  src/pages/NotFound/index.tsx
  src/pages/Trade/Board/index.tsx
  src/pages/Trade/Write/index.tsx
Labels: FEAT
