Repository ODOICHON/frontend, pull requests merged in 2023-07, with the labels that each got.

#131 Feat/#124 이미지 리사이징 적용
  src/constants/image.ts
  src/utils/Quill/imageHandler.ts
Labels: FEAT

#133 Design/#132 게시글 에디터 높이 CSS 수정
  package.json
  src/apis/uploadS3.ts
  src/components/Community/Quill/index.tsx
  src/components/Community/Quill/styles.module.scss
  src/components/Introduce/Quill/index.tsx
  src/components/Introduce/Quill/styles.module.scss
  src/components/Trade/SearchBar/styles.module.scss
  src/hooks/useQuillModules.ts
  src/pages/Trade/styles.module.scss
  src/styles/editor.scss
  src/styles/reset.scss
  src/utils/Quill/imageHandler.ts
  yarn.lock
Labels: REFACTOR, FEAT, DESIGN

#134 fix: 주말의집 -> 주말내집 워딩 수정, logo 변경
  README.md
  index.html
  src/assets/common/logo.svg
  src/components/Common/Footer/index.tsx
  src/components/Common/Preparation/styles.module.scss
  src/components/Terms/index.tsx
  src/constants/main_dummy.ts
  src/pages/Introduce/index.tsx
  src/pages/Main/index.tsx
  src/pages/Trade/Board/index.tsx
  src/pages/Trade/index.tsx
  src/pages/Trade/styles.module.scss
Labels: FIX

#135 Refact/#125: 인트로 / 커뮤니티 / 빈집거래 게시물 Type 리펙토링
  src/apis/boards.ts
  src/apis/login.ts
  src/apis/logout.ts
  src/apis/reissue.ts
  src/apis/uploadS3.ts
  src/assets/main/community1.png
  src/assets/main/community2.png
  src/assets/main/community3.png
  src/components/Board/CommentDetail/index.tsx
  src/components/Board/Comments/index.tsx
  src/components/Board/Like/index.tsx
  src/components/Community/Board/index.tsx
  src/components/Community/Quill/index.tsx
  src/components/Community/Title/index.tsx
  src/components/Introduce/Quill/index.tsx
  src/components/Introduce/ReviewBoard/index.tsx
  src/components/Introduce/TrendBoard/index.tsx
  src/components/Login/AfterLogin/index.tsx
  src/constants/main_dummy.ts
  src/pages/Community/Board/index.tsx
  src/pages/Community/Detail/index.tsx
  src/pages/Introduce/Board/index.tsx
  src/pages/Introduce/index.tsx
  src/pages/Main/index.tsx
  src/types/Board/boardType.ts
  src/types/Board/communityType.ts
  src/types/Board/introType.ts
  src/types/Board/tradeType.ts
  src/types/apiResponseType.ts
  src/types/boardDetailType.ts
  src/types/boardType.ts
  src/types/community.ts
  src/types/error.ts
  src/types/userType.ts
  src/utils/Quill/imageHandler.ts
Labels: REFACTOR, FEAT

#137 design: 게시글 작성에서 스크롤 시 에디터 툴바 화면에 고정
  index.html
  src/components/Community/Quill/styles.module.scss
  src/components/Introduce/Quill/styles.module.scss
  src/styles/editor.scss
  src/styles/reset.scss
Labels: DESIGN

#139 fix: React GA4 적용
  package.json
  src/App.tsx
  src/hooks/useReactGA.ts
  yarn.lock
Labels: FIX

#141 Feat/#140 썸네일 이미지 리사이징 적용
  src/components/Community/Board/index.tsx
  src/components/Introduce/Quill/index.tsx
  src/components/Introduce/ReviewBoard/index.tsx
  src/components/Introduce/TrendBoard/index.tsx
  src/constants/image.ts
  src/pages/Main/index.tsx
  src/styles/reset.scss
Labels: FEAT

#146 Hotfix/#144 이미지 업로드 시 이미지 이름 고유값으로 수정
  package.json
  src/apis/uploadS3.ts
  src/components/Introduce/Quill/index.tsx
  src/utils/Quill/imageHandler.ts
  yarn.lock
Labels: HOTFIX

#145 Hotfix/#144 이미지 업로드 시 이미지 이름 고유값으로 수정
  package.json
  src/apis/uploadS3.ts
  src/components/Introduce/Quill/index.tsx
  src/utils/Quill/imageHandler.ts
  yarn.lock
Labels: HOTFIX

#149 Refact/#148 좋아요 로직 리펙토링 ( 낙관적 업데이트 )
  src/components/Board/Like/index.tsx
Labels: REFACTOR

#147 Feat/#122 빈집거래 매물 상세 페이지 API 연동
  index.html
  src/apis/boards.ts
  src/components/Common/ToastMessage/index.tsx
  src/components/Trade/BoardCard/index.tsx
  src/components/Trade/Info/index.tsx
  src/components/Trade/KakaoMapImage/index.tsx
  src/components/Trade/Report/ReportIcon/index.tsx
  src/components/Trade/Report/ReportModal/index.tsx
  src/components/Trade/Report/ReportModal/styles.module.scss
  src/components/Trade/ScrapIcon/index.tsx
  src/constants/report.ts
  src/pages/Trade/Board/index.tsx
  src/pages/Trade/Board/styles.module.scss
  src/queryClient.ts
  src/styles/reset.scss
  src/types/Board/tradeType.ts
  src/utils/utils.ts
Labels: FEAT

#151 Feat/#150 빈집거래 글쓰기 페이지 퍼블리싱
  src/components/Trade/Quill/index.tsx
  src/components/Trade/Quill/styles.module.scss
  src/constants/trade.ts
  src/pages/Trade/Write/index.tsx
  src/pages/Trade/Write/styles.module.scss
  src/styles/media.scss
Labels: FEAT
