Repository ODOICHON/frontend, pull requests merged in 2023-10, with the labels that each got.

#177 Hotfix/#175 오타, 워딩 수정 (Production)
  src/pages/Trade/Board/index.tsx
  src/pages/Trade/Write/index.tsx
  src/pages/Trade/index.tsx
Labels: HOTFIX

#181 Hotfix/#180 개발용 서버 Code Deploy 코드 작성 (Development)
  .github/workflows/deploy.yml
Labels: CHORE, HOTFIX

#184 fix: github actions 코드 수정
  .github/workflows/deploy.yml
Labels: FIX

#182 Hotfix/#180 개발용 서버 Code Deploy 코드 작성 (Production)
  .github/workflows/deploy.yml
Labels: CHORE, HOTFIX

#174 feat: 마이페이지 home 구현
  src/Routes.tsx
  src/components/MyPage/MyHomeCard/index.tsx
  src/components/MyPage/MyHomeCard/styles.module.scss
  src/components/MyPage/MyHomePopularCard/index.tsx
  src/components/MyPage/MyHomePopularCard/styles.module.scss
  src/pages/Community/Board/index.tsx
  src/pages/Mypage/home/index.tsx
  src/pages/Mypage/home/styles.module.scss
  src/pages/Mypage/styles.module.scss
  src/queryClient.ts
Labels: FEAT

#186 feat: 빈집거래 상세 페이지 수정/삭제 기능 구현
  src/apis/houses.ts
  src/components/Trade/Quill/index.tsx
  src/pages/Trade/Board/index.tsx
  src/pages/Trade/Board/styles.module.scss
  src/pages/Trade/Write/index.tsx
  src/pages/Trade/index.tsx
  src/types/Board/tradeType.ts
Labels: FEAT
