Repository ODOICHON/frontend, pull requests merged in 2023-12, with the labels that each got.

#209 Fix/#208 커뮤니티 페이지에서 게시글 클릭 시, 게시글 상세 페이지로 이동 안되는 버그 수정
  src/pages/Community/Board/index.tsx
Labels: FIX

#211 Refactor/#210 마이페이지 관련 Lazy Loading 제거
  src/Routes.tsx
  src/pages/Mypage/home/index.tsx
  src/pages/Mypage/trade/myself/index.tsx
  src/pages/Mypage/trade/saves/index.tsx
  src/pages/Mypage/trade/scrap/index.tsx
Labels: REFACTOR

#212 Feat/#199 마이페이지 '내가 좋아요 한 게시글' 구현
  src/Routes.tsx
  src/components/MyPage/MyPageNavbar/index.tsx
  src/pages/Mypage/community/likes/index.tsx
  src/pages/Mypage/community/likes/styles.module.scss
  src/queryClient.ts
Labels: FEAT

#217 Fix/#216 매물 상태 변경 모달 전화번호 유효성 검사 정규표현식 수정
  src/Routes.tsx
  src/components/MyPage/DealStateModal/index.tsx
Labels: FIX

#219 Design/#218 빈집거래 스크랩 아이콘
  src/components/Common/ToggleButton/index.tsx
  src/components/Trade/ScrapIcon/index.tsx
  src/components/icons/BookMark/BookmarkFillIcon.tsx
  src/components/icons/BookMark/BookmarkIcon.tsx
Labels: DESIGN

#223 Feat/#203 마이페이지 회원정보 수정 페이지 UI 및 API 연동
  src/Routes.tsx
  src/apis/user.ts
  src/components/Login/AfterLogin/index.tsx
  src/components/MyPage/MySetting/EditInfo/EditEmailInfo/index.tsx
  src/components/MyPage/MySetting/EditInfo/EditEmailInfo/styles.module.scss
  src/components/MyPage/MySetting/EditInfo/EditNicknameInfo/index.tsx
  src/components/MyPage/MySetting/EditInfo/EditNicknameInfo/styles.module.scss
  src/components/MyPage/MySetting/EditInfo/EditPhoneInfo/index.tsx
  src/components/MyPage/MySetting/EditInfo/EditPhoneInfo/styles.module.scss
  src/components/MyPage/MySetting/UserInfo/index.tsx
  src/components/MyPage/MySetting/UserInfo/styles.module.scss
  src/constants/myPage.ts
  src/pages/Login/styles.module.scss
  src/pages/Mypage/setting/CertificateMember/index.tsx
  src/pages/Mypage/setting/CertificateMember/styles.module.scss
  src/pages/Mypage/setting/EditMember/index.tsx
  src/pages/Mypage/setting/EditMember/styles.module.scss
  src/pages/Mypage/setting/EditPassword/index.tsx
  src/pages/Mypage/setting/EditPassword/styles.module.scss
  src/pages/Mypage/setting/WithdrawalFromMembership/index.tsx
  src/pages/Mypage/setting/index.tsx
  src/pages/Mypage/setting/styles.module.scss
  src/pages/SignUp/AgentSignUp/index.tsx
  src/pages/SignUp/index.tsx
  src/pages/SignUp/styles.module.scss
  src/store/certificateStore.ts
  src/types/MyPage/settingType.ts
Labels: FEAT, DESIGN

#221 Feat/#215 회원 탈퇴 컴포넌트 UI 구현 및 API 연동
  src/Routes.tsx
  src/apis/user.ts
  src/constants/myPage.ts
  src/pages/Mypage/community/likes/index.tsx
  src/pages/Mypage/setting/CertificateMember/index.tsx
  src/pages/Mypage/setting/EditMember/index.tsx
  src/pages/Mypage/setting/EditPassword/index.tsx
  src/pages/Mypage/setting/WithdrawalFromMembership/index.tsx
  src/pages/Mypage/setting/WithdrawalFromMembership/styles.module.scss
  src/pages/Mypage/setting/index.tsx
  src/types/Mypage/settingType.ts
Labels: FEAT

#225 fix: types/MyPage 폴더명 대소문자 변경
  src/types/MyPage/settingType.ts
Labels: FIX
