Repository ODOICHON/frontend, pull requests merged in 2023-09, with the labels that each got.

#162 Fix/#161 입주가능 여부에 대한 함수 수정
  src/utils/utils.ts
Labels: FIX

#160 빈집 거래 페이지 개발
  index.html
  package.json
  src/apis/boards.ts
  src/apis/houses.ts
  src/components/Board/Like/index.tsx
  src/components/Common/AccessModal/index.tsx
  src/components/Common/AccessModal/styles.module.scss
  src/components/Common/ToastMessage/index.tsx
  src/components/Community/Title/index.tsx
  src/components/Trade/AddressModal/index.tsx
  src/components/Trade/AddressModal/styles.module.scss
  src/components/Trade/Board/index.tsx
  src/components/Trade/Board/styles.module.scss
  src/components/Trade/BoardCard/index.tsx
  src/components/Trade/CategorySelect/index.tsx
  src/components/Trade/CategorySelect/styles.module.scss
  src/components/Trade/Dropdown/index.tsx
  src/components/Trade/Dropdown/styles.module.scss
  src/components/Trade/FilterOption/index.tsx
  src/components/Trade/FilterOption/styles.module.scss
  src/components/Trade/Info/index.tsx
  src/components/Trade/KakaoMapImage/index.tsx
  src/components/Trade/Quill/index.tsx
  src/components/Trade/Quill/styles.module.scss
  src/components/Trade/Report/ReportIcon/index.tsx
  src/components/Trade/Report/ReportModal/index.tsx
  src/components/Trade/Report/ReportModal/styles.module.scss
  src/components/Trade/ScrapIcon/index.tsx
  src/components/Trade/SearchBar/index.tsx
  src/components/Trade/SearchBar/styles.module.scss
  src/constants/report.ts
  src/constants/trade.ts
  src/constants/trade_dummy.ts
  src/constants/variants.ts
  src/pages/Main/styles.module.scss
  src/pages/Trade/Board/index.tsx
  src/pages/Trade/Board/styles.module.scss
  src/pages/Trade/Write/index.tsx
  src/pages/Trade/Write/styles.module.scss
  src/pages/Trade/index.tsx
  src/pages/Trade/styles.module.scss
  src/queryClient.ts
  src/styles/media.scss
  src/styles/reset.scss
  src/types/Board/tradeType.ts
  src/types/user.d.ts
  src/utils/utils.ts
  yarn.lock
Labels: FEAT

#164 feat: 회원가입 UI 약관추가 및 전체동의 기능 추가, 공인중개사 회원가입 링크 추가
  src/Routes.tsx
  src/components/Terms/MarketingTerm.tsx
  src/components/Terms/PrivacyTerm.tsx
  src/components/Terms/ServiceTerm.tsx
  src/components/Terms/index.tsx
  src/components/Terms/styles.module.scss
  src/pages/AgentSignUp/index.tsx
  src/pages/SignUp/index.tsx
  src/pages/SignUp/styles.module.scss
  src/types/signUp.ts
Labels: FEAT, DESIGN

#167 Feat/#166 공인중개사 회원가입 페이지 UI 및 기능 구현
  src/Routes.tsx
  src/apis/login.ts
  src/components/Common/Footer/index.tsx
  src/components/Common/Footer/styles.module.scss
  src/components/Terms/AgentTerm.tsx
  src/components/Terms/MarketingTerm.tsx
  src/components/Terms/PrivacyTerm.tsx
  src/components/Terms/ServiceTerm.tsx
  src/components/Terms/index.tsx
  src/components/Trade/AddressModal/index.tsx
  src/pages/AgentSignUp/index.tsx
  src/pages/Login/index.tsx
  src/pages/SignUp/AgentSignUp/index.tsx
  src/pages/SignUp/AgentSignUp/styles.module.scss
  src/pages/SignUp/index.tsx
  src/pages/SignUp/styles.module.scss
  src/pages/Trade/Write/index.tsx
  src/queryClient.ts
  src/styles/reset.scss
  src/types/signUp.ts
  src/types/user.d.ts
Labels: FEAT, DESIGN

#169 chore: 구글 태그매니저 적용
  package.json
  src/App.tsx
  src/hooks/useReactGTM.ts
  yarn.lock
Labels: CHORE

#171 공인중개사 회원 배포
  package.json
  src/App.tsx
  src/Routes.tsx
  src/apis/login.ts
  src/components/Common/Footer/index.tsx
  src/components/Common/Footer/styles.module.scss
  src/components/Terms/AgentTerm.tsx
  src/components/Terms/MarketingTerm.tsx
  src/components/Terms/PrivacyTerm.tsx
  src/components/Terms/ServiceTerm.tsx
  src/components/Terms/index.tsx
  src/components/Terms/styles.module.scss
  src/components/Trade/AddressModal/index.tsx
  src/hooks/useReactGTM.ts
  src/pages/Login/index.tsx
  src/pages/SignUp/AgentSignUp/index.tsx
  src/pages/SignUp/AgentSignUp/styles.module.scss
  src/pages/SignUp/index.tsx
  src/pages/SignUp/styles.module.scss
  src/pages/Trade/Write/index.tsx
  src/queryClient.ts
  src/styles/reset.scss
  src/types/signUp.ts
  src/types/user.d.ts
  yarn.lock
Labels: FEAT
