Repository ODOICHON/frontend, pull requests merged in 2023-05, with the labels that each got.

#75 feat : 커뮤니티 라우팅 구조 설계
  src/Routes.tsx
  src/pages/Community/AdvertisementBoard/index.tsx
  src/pages/Community/AdvertisementBoard/styles.module.scss
  src/pages/Community/FreeBoard/index.tsx
  src/pages/Community/FreeBoard/styles.module.scss
  src/pages/Community/index.tsx
  src/pages/Community/styles.module.scss
Labels: FEAT

#76 feat : 커뮤니티 페이지 UI 구현
  .eslintrc.json
  src/Routes.tsx
  src/assets/common/nextArrow.svg
  src/assets/common/prevArrow.svg
  src/components/Community/Board/index.tsx
  src/components/Community/Board/styles.module.scss
  src/constants/category.ts
  src/constants/community_dummy.ts
  src/pages/Community/AdvertisementBoard/index.tsx
  src/pages/Community/AdvertisementBoard/styles.module.scss
  src/pages/Community/Board/index.tsx
  src/pages/Community/Board/styles.module.scss
  src/pages/Community/FreeBoard/index.tsx
  src/pages/Community/FreeBoard/styles.module.scss
  src/pages/Community/index.tsx
  src/pages/IntroBoard/styles.module.scss
  src/pages/IntroWrite/index.tsx
  src/reset.scss
  src/types/boardType.ts
  src/types/community.ts
Labels: FEAT, STYLE

#79 style : 커뮤니티 페이지 반응형 UI 적용
  src/pages/Community/Board/styles.module.scss
Labels: FIX, STYLE

#84 hotfix : 게시글 리스트 조회 API 변동에 따른 운영환경 API 호출 코드 수정 핫픽스
  .gitignore
  src/components/BoardComponents/Like/index.tsx
  src/pages/Introduce/index.tsx
  src/pages/Main/index.tsx
Labels: FIX

#82 Feat/#80 커뮤니티 페이지 API 연동
  src/Routes.tsx
  src/components/AfterLogin/index.tsx
  src/components/AfterLogin/styles.module.scss
  src/components/Community/Board/index.tsx
  src/components/Community/Board/styles.module.scss
  src/components/Introduce/ReviewBoard/index.tsx
  src/components/Introduce/ReviewBoard/styles.module.scss
  src/components/Introduce/TrendBoard/index.tsx
  src/components/Introduce/TrendBoard/styles.module.scss
  src/components/Pagenation/index.tsx
  src/components/Pagenation/styles.module.scss
  src/constants/category.ts
  src/constants/community_dummy.ts
  src/pages/Community/Board/index.tsx
  src/pages/Community/Board/styles.module.scss
  src/pages/Community/styles.module.scss
  src/pages/Introduce/Board/index.tsx
  src/pages/Introduce/Board/styles.module.scss
  src/pages/Introduce/Write/index.tsx
  src/pages/Introduce/Write/styles.module.scss
  src/pages/Introduce/index.tsx
  src/pages/Main/index.tsx
  src/types/boardType.ts
  src/utils/Quill/getImageUrls.ts
  src/utils/utils.ts
Labels: REFACTOR, FEAT

#94 Design/#91 커뮤니티 상세 게시판 페이지 UI 수정
  src/pages/Community/Detail/styles.module.scss
Labels: DESIGN

#92 Design/#86 배너 이미지 크기 수정, 게시글 폰트 사이즈 수정
  src/pages/Community/Detail/styles.module.scss
  src/pages/Introduce/Board/styles.module.scss
  src/pages/Main/styles.module.scss
  src/reset.scss
Labels: DESIGN

#95 Design/#93 404 Not Found 페이지 적용, 게시글 없을 때 컴포넌트 추가
  src/Routes.tsx
  src/assets/common/crash-logo.svg
  src/components/Footer/index.tsx
  src/components/Footer/styles.module.scss
  src/components/NoPosts/index.tsx
  src/components/NoPosts/styles.module.scss
  src/pages/Community/Board/index.tsx
  src/pages/Community/Detail/index.tsx
  src/pages/Introduce/Board/index.tsx
  src/pages/NotFound/index.tsx
  src/pages/NotFound/styles.module.scss
Labels: FEAT, DESIGN

#98 refact: axios interceptor 코드 커스텀훅으로 작성하여 컴포넌트와 분리
  src/App.tsx
  src/hooks/useAxiosInterceptor.ts
  src/pages/_layout.tsx
Labels: REFACTOR

#102 chore: React GA Initialize 코드 적용
  package.json
  src/App.tsx
  yarn.lock
Labels: CHORE

#103 Feat/#90 메인페이지 게시글 api 연동
  src/pages/Introduce/index.tsx
  src/pages/Main/index.tsx
  src/types/boardType.ts
Labels: FEAT
