Repository ODOICHON/frontend, pull requests merged in 2024-05, with the labels that each got.

#245 Feat/#244 커뮤니티 페이지에서 검색 시, 글자 조합이 완성되지 않은 경우 모달창 띄우기
  src/hooks/useToastMessageType.ts
  src/pages/Community/Board/index.tsx
  src/utils/utils.ts
Labels: FEAT

#247 Feat/#246 자유게시판 게시글 작성시 말머리 미선택해도 게시글 작성 가능하게 구현
  src/components/Community/Board/index.tsx
  src/components/Community/Quill/index.tsx
  src/components/Introduce/Quill/index.tsx
  src/pages/Community/Detail/index.tsx
  src/pages/Community/Detail/styles.module.scss
  src/styles/editor.scss
  src/utils/utils.ts
Labels: FEAT

#249 Feat/#248 홍보, 자유 게시판 댓글 삭제 시, 모달창 띄우기
  src/components/Board/CommentDetail/index.tsx
  src/components/Board/Comments/index.tsx
  src/hooks/useToastMessageType.ts
Labels: FEAT

#251 fix: 마켓팅 -> 마케팅 워딩 수정
  src/components/Terms/MarketingTerm.tsx
  src/pages/SignUp/AgentSignUp/index.tsx
  src/pages/SignUp/index.tsx
Labels: FIX

#253 fix: 메인페이지 트랜드 -> 트렌드 워딩 수정
  src/pages/Main/index.tsx
Labels: FIX

#256 Design/#255 댓글 버튼 UI 수정
  src/components/Board/Comments/index.tsx
  src/components/Board/Comments/styles.module.scss
Labels: STYLE

#260 Fix/#259 CloudFront CDN 서버에서 가져오는 이미지를 S3에서 직접 가져오도록 수정합니다.
  src/components/Introduce/Quill/index.tsx
  src/pages/Trade/Write/index.tsx
  src/utils/Quill/imageHandler.ts
Labels: FIX

#261 일부 QA 적용 및 이미지 불러오는 저장소 CloudFront -> S3로 변경 후 운영서버 배포
  src/components/Board/CommentDetail/index.tsx
  src/components/Board/CommentDetail/styles.module.scss
  src/components/Board/Comments/index.tsx
  src/components/Board/Comments/styles.module.scss
  src/components/Community/Board/index.tsx
  src/components/Community/Quill/index.tsx
  src/components/Introduce/Quill/index.tsx
  src/components/Terms/MarketingTerm.tsx
  src/hooks/useToastMessageType.ts
  src/pages/Community/Board/index.tsx
  src/pages/Community/Detail/index.tsx
  src/pages/Community/Detail/styles.module.scss
  src/pages/Introduce/Board/index.tsx
  src/pages/Main/index.tsx
  src/pages/SignUp/AgentSignUp/index.tsx
  src/pages/SignUp/index.tsx
  src/pages/Trade/Write/index.tsx
  src/styles/editor.scss
  src/utils/Quill/imageHandler.ts
  src/utils/utils.ts
Labels: FIX, FEAT, DESIGN

#266 chore: 운영, 개발 환경에 따른 appspec.yml, deploy.yml 수정
  .github/workflows/deploy.yml
  appspec.yml
Labels: CHORE

#269 docs: deploy.yml 수정
  .github/workflows/deploy.yml
Labels: DOCS

#270 appspec.yml과 deploy.yml을 운영, 개발 환영에 맞춰서 수정
  .github/workflows/deploy.yml
  appspec.yml
Labels: CHORE
