Repository ODOICHON/frontend, pull requests merged in 2024-08, with the labels that each got.

#282 design: 키워드 변경 (빈집거래 -> 농가거래)
  src/components/Common/Footer/index.tsx
  src/components/Common/Navbar/index.tsx
  src/components/Common/ToggleMenu/index.tsx
  src/pages/MyPage/home/index.tsx
  src/pages/Trade/Board/index.tsx
  src/pages/Trade/Process/index.tsx
  src/pages/Trade/Write/index.tsx
  src/pages/Trade/index.tsx
  src/utils/utils.ts
Labels: DESIGN

#283 feat: 농가 거래 페이지 검색 필터에서 새로운 유형 타입 추가 & 기존 유형 타입을 거래 타입으로 변경
  src/components/Trade/Dropdown/index.tsx
  src/components/Trade/SearchBar/index.tsx
  src/constants/trade.ts
  src/pages/Trade/index.tsx
  src/types/Board/tradeType.ts
  src/utils/utils.ts
Labels: FEAT

#287 Feat/#284 농가 거래 등록 페이지에 등록해야하는 목록 수정 및 기능 추가
  src/pages/Trade/Write/index.tsx
  src/pages/Trade/Write/styles.module.scss
  src/types/Board/tradeType.ts
  src/utils/utils.ts
Labels: REFACTOR

#286 농가 거래 상세 페이지에서 유형 정보 추가 및 게시글 제목 말머리에 유형 추가
  src/components/Trade/Board/index.tsx
  src/components/Trade/Info/index.tsx
  src/pages/Trade/Board/index.tsx
  src/pages/Trade/index.tsx
  src/types/Board/tradeType.ts
  src/utils/utils.ts
Labels: FEAT

#289 feat: 공인중개사 상세 설명 타입 추가
  src/pages/Trade/Write/index.tsx
  src/types/Board/tradeType.ts
Labels: FEAT

#292 Feat/#291 농가 거래 작성 페이지에 '상세 설명' 목록 추가 ( 공인중개사 일 때 )
  src/pages/Trade/Write/index.tsx
  src/utils/utils.ts
Labels: FEAT

#293 feat: 농가 거래 상세 페이지 UI 수정
  src/components/Trade/Info/index.tsx
  src/pages/Trade/Board/index.tsx
  src/pages/Trade/Board/styles.module.scss
Labels: FIX, FEAT

#279 fix: refresh 토큰 만료 시 사용자에게 Alert를 보여주지 않도록 설정합니다.
  src/apis/reissue.ts
Labels: FIX

#272 Design/#271 중개 프로세스 문서 이미지 순서 변경 및 캡션 적용
  src/assets/trade/example1.jpg
  src/assets/trade/example1.png
  src/assets/trade/example2.jpg
  src/assets/trade/example2.png
  src/assets/trade/example3.jpg
  src/assets/trade/example3.png
  src/pages/Trade/Process/index.tsx
  src/pages/Trade/Process/styles.module.scss
Labels: DESIGN

#277 fix: 메인페이지 오도이촌 소개, 오도이촌 커뮤니티 콘텐츠 카드 슬라이더 순환하도록 수정
  package.json
  src/hooks/useSwiperRef.ts
  src/pages/Introduce/index.tsx
  src/pages/Main/index.tsx
  src/pages/Trade/Board/index.tsx
  yarn.lock
Labels: FIX

#258 feat: 주소 찾기 모달 닫는 기능 추가
  src/components/Trade/AddressModal/index.tsx
Labels: FEAT

#296 TradeBoard에 houseType prop이 생김에 따라 props 전달이 되지 않은 컴포넌트 수정
  src/pages/MyPage/home/index.tsx
  src/pages/MyPage/trade/scrap/index.tsx
Labels: FIX

#298 개발서버 관련 github action 코드 수정
  .github/workflows/deploy.yml
Labels: FIX

#294 농가거래 서비스 배포
  .github/workflows/deploy.yml
  package.json
  src/apis/reissue.ts
  src/assets/trade/example1.jpg
  src/assets/trade/example1.png
  src/assets/trade/example2.jpg
  src/assets/trade/example2.png
  src/assets/trade/example3.jpg
  src/assets/trade/example3.png
  src/components/Common/Footer/index.tsx
  src/components/Common/Navbar/index.tsx
  src/components/Common/ToggleMenu/index.tsx
  src/components/Trade/AddressModal/index.tsx
  src/components/Trade/Board/index.tsx
  src/components/Trade/Dropdown/index.tsx
  src/components/Trade/Info/index.tsx
  src/components/Trade/SearchBar/index.tsx
  src/constants/trade.ts
  src/hooks/useSwiperRef.ts
  src/pages/Introduce/index.tsx
  src/pages/Main/index.tsx
  src/pages/MyPage/home/index.tsx
  src/pages/MyPage/trade/scrap/index.tsx
  src/pages/Trade/Board/index.tsx
  src/pages/Trade/Board/styles.module.scss
  src/pages/Trade/Process/index.tsx
  src/pages/Trade/Process/styles.module.scss
  src/pages/Trade/Write/index.tsx
  src/pages/Trade/Write/styles.module.scss
  src/pages/Trade/index.tsx
  src/types/Board/tradeType.ts
  src/utils/utils.ts
  yarn.lock
Labels: FEAT
